name: credit_card_reader
description: technical assesment

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  isar: ^3.1.0+1
  hooks_riverpod: ^2.3.6
  google_fonts: ^5.0.0
 # cached_network_image: ^3.2.3
  flutter_svg: ^1.1.6
  awesome_dialog: ^2.2.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  go_router: ^8.0.1
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  isar_generator: ^3.1.0+1

global_options:
  freezed:freezed:
    runs_before:
      - isar_generator:isar_generator

  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/icons/

